CREATE TABLE IF NOT EXISTS user_role (
  role_id        INT PRIMARY KEY,
  role_name      TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS library (
  library_id     INT PRIMARY KEY,
  name           TEXT NOT NULL,
  address        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_user (
  user_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  library_id     INT NOT NULL REFERENCES library(library_id),
  role_id        INT NOT NULL REFERENCES user_role(role_id),
  name           TEXT NOT NULL,
  address        TEXT NOT NULL,
  date_of_birth  DATE NOT NULL,
  email          TEXT NOT NULL UNIQUE,
  password_hash  TEXT NOT NULL,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS book (
  book_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              TEXT NOT NULL,
  author             TEXT NOT NULL,
  isbn               TEXT,
  publication_year   INT,
  category           TEXT
);

CREATE TABLE IF NOT EXISTS item (
  item_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id         INT NOT NULL REFERENCES book(book_id) ON DELETE CASCADE,
  library_id      INT NOT NULL REFERENCES library(library_id),
  item_condition  TEXT NOT NULL,
  shelf_mark      TEXT NOT NULL,

  CONSTRAINT chk_item_condition
    CHECK (item_condition IN ('new','good','average','worn'))
);

CREATE TABLE IF NOT EXISTS loan (
  loan_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id      INT NOT NULL REFERENCES item(item_id),
  user_id      INT NOT NULL REFERENCES app_user(user_id),
  loan_date    TIMESTAMPTZ NOT NULL,
  due_date     DATE NOT NULL,
  return_date  TIMESTAMPTZ NULL,
  fine_paid    NUMERIC(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS reservation (
  reservation_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id            INT NOT NULL REFERENCES book(book_id) ON DELETE CASCADE,
  user_id            INT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
  queue_number       INT NOT NULL,
  reservation_date   TIMESTAMPTZ NULL,
  expiry_date        DATE NULL,
  status             TEXT NOT NULL,

  CONSTRAINT uq_reservation_queue UNIQUE (book_id, queue_number),

  CONSTRAINT chk_reservation_status
    CHECK (status IN ('pending','ready','expired','fulfilled'))
);

CREATE INDEX IF NOT EXISTS idx_reservation_book_status_queue
  ON reservation(book_id, status, queue_number);

CREATE INDEX IF NOT EXISTS idx_loan_item_active
  ON loan(item_id)
  WHERE return_date IS NULL;

CREATE INDEX IF NOT EXISTS idx_loan_user
  ON loan(user_id);
